### ISSUE TITLE
Рвется цепочка Undo при Ctrl-Del (удалении выделенного текста)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sensboston/fictionbookeditor#174]
```
Создать новый документ, написать абзац, 
например "Чертята чертят чернилами.". 
выделить слово "чертят", нажать Ctrl-Del. Это 
удалит слово "чертят", но проблема в том, что 
после этого нельзя сделать откат (Undo).

Проявляется в FBE 2.6 Release.
WinXP SP3 Rus, IE 6.0.2900.5512.
```

Original issue reported on code.google.com by `scl...@gmail.com` on 3 Jan 2011 at 6:44

**Comment by Sclex** [comment]
Оказывается, такая ошибка возникает, если включено отображение неразрывных пробелов другим символом (например, квадратиком). Сформулировал более общее issue:

https://github.com/sensboston/fictionbookeditor/issues/205
