### ISSUE TITLE
Проблема с inline image в стихах

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sensboston/fictionbookeditor#183]
```
Какие шаги приводят к проблеме?
1. Вставляем картинку внутри строфы стиха
2. Сохраняем документ

Что должно произойти?
Картинка должна вставиться в текст как inline, 
что-то вроде такого:

     <v>Это рисунок <image l:href="#img7F68.png"/> в строфе.</v>

Что реально происходит?
Картинка разрывает строфу так:

     <v>Это рисунок </v>
     <image l:href="#img7F68.png"/>
     <v> в строфе.</v>

При этом валидатор (FBV) работает правильно. 
В режиме Source всё отображается правильно, но 
в режиме В (и в сохранённом на диск 
документе) - с разрывом.

Какую версию программы вы используете?
2.6

Под какой версией операционной системы?
Windows Vista + последние обновления

Какая версия Internet Explorer установлена в вашей 
системе?
IE 9.
```

Original issue reported on code.google.com by `vadim.do...@gmail.com` on 10 Aug 2011 at 3:26

**Comment by Sclex** [comment]
Как исправить данный баг (и несколько аналогичных, с тегами th, th и ) в уже установленной версии FBE, описано здесь:
https://pastebin.com/1kjgW7p6
Топик в гугль-группе, посвященный данному багу:
https://groups.google.com/forum/#!topic/fiction-book-editor/mlqcY74cjdY

**Comment by Sclex** [comment]
Да, забыл сказать: это исправление внесено в исходники FBE в хранилище sens.boston-а здесь, на GitHub-е, так что в следующей версии FBE, когда она будет выпущена, данный issue должен быть уже неактуален.
