### ISSUE TITLE
Заголовок для стиля <poem>

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sensboston/fictionbookeditor#188]
```
Активировать в меню FBE добавление 
заголовка <body> для стиля <poem>
```

Original issue reported on code.google.com by `rona...@gmail.com` on 14 Oct 2012 at 9:32

**Comment by Sclex** [comment]
Сделан такой скрипт (правда выделение заголовком не делает, а только добавляет пустой заголовок стиху):
https://groups.google.com/forum/#!topic/fiction-book-editor/vs2Spr09kRE
Скрипт должен войти в следующую версию FBE.
