### ISSUE TITLE
Сноска в эпиграфе

### ISSUE THREAD

**Issue by GoogleCodeExporter** [sensboston/fictionbookeditor#193]
```
Если делать эпиграф из предложения со 
сноской, то вырезается ссылка на сноску, а 
номер сноски (например [1]) становится 
текстом.

FBE 2.6.5, 2.6.6; Win XP, 7

```

Original issue reported on code.google.com by `ivari...@gmail.com` on 25 Jan 2013 at 8:57

**Comment by Sclex** [comment]
Исправлено. Теперь при создании эпиграфа из выделенного текста форматирование, содержавшееся в этом выделенном тексте, будет сохраняться.
