### ISSUE TITLE
И как его собрать из сырцов? 

### ISSUE THREAD

**Issue by KarelWintersky** [sensboston/fictionbookeditor#206]
Собственно, сабж.

makefile пуст :(

**Comment by sensboston** [comment]
Попробую проверить (100500 лет не трогал), должно собираться "на раз".

**Comment by KarelWintersky** [comment]
```
all: tFBE

clean:
	-del /q genres.txt
	devenv FBE.sln /clean Release

genres.txt: root_genres.xml gtrans.xsl
	msxsl root_genres.xml gtrans.xsl -o genres.txt

tFBE: genres.txt
	devenv FBE.sln /build Release
```
Все что есть в предыдущей версии makefile...

**Comment by sensboston** [comment]
Он там был пустой "по жизни", никто никогда не экспортировал makefile, всегда собиралось из-под VS.
Я попробую проапдетить и собрать из-под VS 2022 community edition (в текущем состоянии он собирался аж.. под VS 2010 😜 )

**Comment by sensboston** [comment]
Выбрал время сегодня, попробовал: есть хорошая новость и плохая 😉 
Из моего архива собирается и даже работает:

![fbe](https://user-images.githubusercontent.com/1036158/230791196-04782559-221e-48e5-93ee-8e75b8528f65.jpg)
(но, что любопытно, только в Release конфигурации - в Debug пишет, что все ОК, но FBE.exe не создается 🤣 ), но только Visual Studio 2013 с тулсетом Windows XP v120_xp

![fbe2](https://user-images.githubusercontent.com/1036158/230791206-76d0ebe8-49e9-407f-8b08-3b736d0f5eeb.jpg)

Плохая новость в том, что в более старших версиях Visual Studio, даже с использованием этого тулсета, возникают проблемы.

@KarelWintersky , если вам действительно интересно поработать и улучшить FBE, то я могу выложить архив, но разбираться придется вам самому (а там много с чем придется разбираться, нужно ставить старый Windows SDK, VS и т.д.). Если же вы спрашивали из чистого любопытства, лишь проглядев отсутствующий makefile, то я не могу тратить на это свое время.

**Comment by Sclex** [comment]
sensboston, может, соберешь новую версию установочного пакета FBE с последниями версиями скриптов и прочих файлов? А то давно уже никто его не собирал.

**Comment by Sclex** [comment]
@sensboston, если у тебя есть инсталлятор NSIS, необходимый для сборки инсталла FBE, то, может, стоит залить его (инсталлятор) в GitHub-хранилище исходников FBE? Чтобы обезопаситься от возможной утраты его. Кто-то писал, что в интернете уже невозможно найти версию инсталлятора NSIS, годную для сборки инсталла FBE.

**Comment by Sclex** [comment]
@sensboston, версия FBE Release 2.6.6 была собрана 6 апреля 2012 года. Уже 11 лет прошло с того момента, и за это время было сделано много хороших изменений в плане скриптов.

**Comment by sensboston** [comment]
О, @Sclex, привет, стопятьсот лет не виделись, рад тебя слышать! Надеюсь, все у тебя OK!

Согласен, в предложении сделать новую сборку с обновленными скриптами есть смысл. У меня, **естественно**, всё осталось 😉 - с современными ценами на хранение информации смысл что-то удалять пропадает, так, что я храню абсолютно всё, как в локальных бэкапах, так и в облачных. 

Повожусь "по свободе" с инсталлятором: попробую собрать с наиболее актуальным бинарником (кстати, у меня установлена "официальная" версия 2.6.7 от 11 ноября 2014 года, там старина **TaF** что-то фиксил, как припоминаю
<img src="https://user-images.githubusercontent.com/1036158/230917731-ce7fcd58-1b72-412d-871d-eab4c886c5ae.jpg"  width="400px" /> 
)  и последними скриптами из этой "репы", но нужно будет протестировать всё тщательно, думаю, ты поможешь.

**Comment by Sclex** [comment]
@sensboston, одно из изменений, которые сделал TaF, - он перевел FBE с использования MSXML4 на MSXML6.

> нужно будет протестировать всё тщательно, думаю, ты поможешь.
Тестер из меня негодный, я даже свои собственные скрипты не способен протестировать как следует.

**Comment by sensboston** [comment]
Ну, выкладывать в публичный доступ неоттестированый релиз не "комильфо" - нужен кто-то, кто смог бы его "прогнать" хотя-бы обычной работой над документом (я не говорю о полном, профессиональном тестировании), и "прогоном" всех, включенных в релиз скриптов (бинарники я трогать не хочу, потому, что не уверен, что у меня действительно последняя копия; в этой "репе", которая была перенесена "на автомате", я тоже не уверен).

**Comment by Sclex** [comment]
@sensboston, может, stokber согласится заняться тестированием. Он мне в последнее время помогал с тестированием моих скриптов. Кроме него, постоянных тестеров сейчас и нет.

Тестировать ВСЕ имеющиеся скрипты - какой смысл? С чего бы им работать неправильно?

**Comment by Sclex** [comment]
> Ну, ты же сам написал "я даже свои собственные скрипты не способен протестировать как следует"

Да, но мои скрипты УЖЕ тестировались другими людьми (в основном TaKir-ом и stokber-ом). Я исправил все баги моих скриптов, о которых (багах) было сообщено - кроме только одного или двух незначительных недочетов в скрипте "Обзор и превращение элементов". Поэтому счас подходящий момент, чтобы сделать установочный пакет FBE - работа старых скриптов налажена, а новые скрипты (с новыми багами) еще не начаты.

Кроме скриптов, надо заменить файлы main.js и fb2.xsl.

main.js для бинарников от FBE 2.6.7 надо взять вот этот:
https://raw.githubusercontent.com/sensboston/fictionbookeditor/master/files/main.for_FBE_2.6.7.js

Да, и надеюсь, ты помнишь, что файлы скриптов находятся не только в папке Scripts, но еще и в папке HTML.

Вроде это все, что тебе надо знать для замены старых файлов на новые.

**Comment by Sclex** [comment]
@sensboston, новая версия FBE будет иметь номер 2.7.0, согласен?

**Comment by sensboston** [comment]
Инсталлятор можем назвать, как угодно, но в бинарнике (AboutBox-е) останется старая версия.

**Comment by Sclex** [comment]
@sensboston, а, ну да, ты же возьмешь старый бинарник, а в нем прописан старый номер версии. Это мне не нравится. SeNS, посмотри вот здесь: https://github.com/ArgusC/FBE/releases - там в разделе Assets есть "Source code". По идее, это исходники TaF-овой версии 2.6.7. Может, ты соберешь инсталл из них? ArgusC - это другой ник TaF-а.

**Comment by sensboston** [comment]
Нет, новый бинарник (точнее, бинарники - там же не один exe, а еще куча всего) я собирать однозначно не буду; я же написал, что он-то собирается, но как-то странно. В "репе" TaF-а не весь код, а лишь малые части. Максимум, что можно попробовать, так это изменить в hex-editore дату и номер билда (чисто для "визуальности"), но не уверен, что это сработает (контрольные суммы там etc.)

**Comment by Sclex** [comment]
@sensboston, а почему бы не собрать инсталл FBE в Visual Studio 2010? Мне кажется, надо для компиляции бинарников использовать "родную" для исходников FBE версию MS VC.

**Comment by Sclex** [comment]
Поправка: "версию MS VS".

**Comment by sensboston** [comment]
Я же написал, что я не хочу этим заниматься: нет особо ни времени, ни желания. И, главное, для чего? Чтобы циферки релиза подправить? "Вам шашечки, или ехать"? Тем более, что с компиляцией всё совсем не просто - нет ни достоверно подтвержденных сорцов версии 2.6.7, для сборки требуются старые SDK и т.п.

**Comment by Sclex** [comment]
ОК, ясно.

**Comment by Sclex** [comment]
@sensboston, я когда-то собирал FBE из исходников, так, помнится, пришлось установить только Visual Studio и инсталлятор NSIS. Про SDK (тем более во множественном числе) что-то ничего не припоминаю.

**Comment by KarelWintersky** [comment]
Да мне бы просто актуальный бинарник... Все таки сколько лет прошло - неужели не было никаких обновлений? ;-)

Так-то я не сишник. Ну то есть собрать по инструкции смогу, но разбираться "что почему как сломалось"..

Кстати, под линукс FBE не портируется?

**Comment by Sclex** [comment]
Тема TaF-а про его версии FBE:
https://flibusta.is/node/407253

**Comment by Sclex** [comment]
> Кстати, под линукс FBE не портируется?

FBE в качестве WYSIWYG-редактора использует Internet Exporer, так что под линуксом FBE можно запускать разве что под WINE-ом (если это вообще возможно). Вы, я так понимаю, имели в виду, можно ли из исходников FBE собрать программу для Linux-а (которую можно запускать _без_ WINE-а).

Я использую FBE в Линуксовой виртуальной машине Oracle VM VirtualBox. Вполне доволен.

**Comment by Sclex** [comment]
@KarelWintersky, а что, в тех бинарниках, которые уже есть, вам чего-то не хватает?

**Comment by KarelWintersky** [comment]
> а что, в тех бинарниках, которые уже есть, вам чего-то не хватает?

... ну.. за эти годы не было никаких изменений и дополнений?

**Comment by sensboston** [comment]
@Sclex, повозился чуток с инсталлятором, думаю, этого будет достаточно. Даже пофиксил систему автоапдейтов (из AboutBox-а). Инструкция находится вот тут: https://github.com/sensboston/fictionbookeditor/tree/master/Setup 
Тестовый релиз 2.7.0 со свежими скриптами пока лежит вот тут: https://senssoft.com/fbe/setup.exe , но в будущем ты сможешь выкладывать его куда угодно, хоть и сюда, на GitHub. Единственно, должна быть прямая ссылка на скачивание .exe (то, что у GitHub-а называется raw file)

@KarelWintersky, все, что были в бинарниках, есть в 2.6.7 (а теперь уже в 2.7.0), больше никто ничего не делал (да, наверное, и не нужно). Да, под Ubuntu FBE работает (см. архивированную wiki https://code.google.com/archive/p/fictionbookeditor/wikis/FbeInUbuntu.wiki )

**Comment by sensboston** [comment]
@Sclex, перевыложил релиз сюда, на GitHub, и заодно поправил update.xml (для примера).

**Comment by Sclex** [comment]
@sensboston, нельзя ли изменить имя папки (по умолчанию), в которую устанавливается FBE? Я имею в виду, чтобы номер версии (в названии папки) был 2.7.0?
![Clipboard34](https://user-images.githubusercontent.com/26221736/231099123-42073f39-479f-416c-b967-05482ef96689.png)

**Comment by Sclex** [comment]
Вернее, это имя папки в меню "Пуск".

**Comment by Sclex** [comment]
Версия 2.7.0 установилась у меня без всяких проблем и работает. Скрипты в ней новые. Только с папкой HTML не все в порядке.

**Comment by Sclex** [comment]
Папки, вложенные в папку HTML, то есть папки CSS и Images, надо обновить тоже.

**Comment by Sclex** [comment]
О-о, так в окошке "О программе" показывается номер версии 2.7.0. Отлично, супер!

**Comment by Sclex** [comment]
@sensboston, вот еще о чем хочу сказать. FBE 2.6.6 использовал MSXML4. А FBE 2.6.7 - вроде как MSXML6. В инсталляторе версии 2.7.0 какая прописана проверка - чтобы был установлен MSXML4 или MSXML6? А то может получиться, что инсталлятор для установки будет требовать MSXML4, хотя реально для работы FBE эта версия MSXML не нужна. Надо бы проверить этот момент.

**Comment by sensboston** [comment]
@Sclex, отвечу по порядку:

1. Пожалуйста, всегда обращайтесь! 😉 
2. Можно, изменил (кстати, NSIS-овские скрипты ну очень простые, куда проще JS)
3. Думал предложить тебе это в качестве практического упражнения, но вспомнил, что я и инсталляционный скрипт изменил, потому - перевыложил новый релиз. Но в следующий раз ты уж сам попробуй, ОК?
4. Да, и номер правильный показывается, и ссылка ведёт туда, куда положено, и система проверки апдейтов работает. Там "хитрость" была в том, что при изменении exe-шника нужно было уложиться в определённую длину строки (т.е. количество байт). Решил с помощью настройки форвардингов (UrlRewrite) на моем сайте, senssoft.com
5. В инсталляторе **проверяется MSXML6**, только, по моему, это еще я сделал когда-то, а не TuF (точно можно сказать, лишь посмотрев историю коммитов, ну, да это не принципиально).

**Comment by Sclex** [comment]
В новой версии скрипты с диалогами работают, как и должны. Отлично, спасибо!

**Comment by sensboston** [comment]
Давай я поясню, как это работает (видимо, инструкция не до конца понятной получилась):
- используется только NSIS (и только та версия, что в Setup, с тем-же UAC пакетом - они в последних версиях ну просто всё изменили, надо скрипт переписывать)
- файлы берутся из папки **Setup/Installer/Input**; все бинарники там от 2.6.7 версии, только я изменил строки в FBE.exe, и с помощью утилитки update_fbe.exe мы меняем **внутри экзешника** номер и дату билда
- при создании новой инсталляции просто копируй свои изменения (скриптов и прочего, HTML там etc.) в папку **Setup/Installer/Input** - это как бы точная копия того, что будет у юзера на диске, меняй номер билда в exe-шнике и NSIS-овском инсталляционном скрипте, и запускай батник

**Comment by Sclex** [comment]
@sensboston, инструкция-то, может, и понятная, просто я, честно говоря, пока в нее не вникал. Спасибо за дополнительные разъяснения.

**Comment by sensboston** [comment]
@Sclex, кстати, у тебя какой-то мессенджер, постоянно работающий, есть? Ну, и/или рабочее "мыло"? Скинь на моё "мыло", прописанное на https://senssoft.com (там оно картинкой 😉 ) - иногда, редко, бывает нужда в сложных regexp-ах, я с ними традиционно "не дружу", а ты у нас - спец.

**Comment by Sclex** [comment]
@sensboston, вчера я позапускал почти все скрипты, входящие в состав FBE 2.7.0. В целом все работает хорошо, но обнаружилось 3 ошибки в скриптах. Две из них я исправил (одна из которых серьезная - скрипт удалял атрибуты id, которые он не должен удалять). Еще один баг собираюсь исправить (скрипт "Перейти на предыдущий курсив" и аналогичные - устанавливают курсор в неверную позицию). Так что пока что выпуск новой версии еще не объявляем для всех. Когда исправлю остающуюся ошибку, попытаюсь собрать установочный пакет самостоятельно.

stokber-а я уведомил о новой версии инсталла FBE, он уже тестирует ее - пока ни о каких ошибках не сообщал, пишет, что "полет нормальный".

**Comment by Sclex** [comment]
@sensboston, Release 2.7.0 на GitHub-е я удалил. Думаю, не стоит не доведенные до максимально хорошего состояния версии инсталла выкладывать для всех. А то расползутся по интернету версии с разными там недостатками. Если понадобится переслать инсталл от тебя ко мне, ты можешь использовать электронную почту.

**Comment by Sclex** [comment]
Скрипты "Перейти на предыдущий курсив" и аналогичные - я уже исправил.

**Comment by sensboston** [comment]
>> ты можешь использовать электронную почту
https://github.com/sensboston/fictionbookeditor/issues/206#issuecomment-1503427204

**Comment by Sclex** [comment]
@sensboston, я присылал тебе на почту адрес моей почты. Разве мое сообщение к тебе не пришло?

**Comment by sensboston** [comment]
Нет, не пришло.

**Comment by Sclex** [comment]
@sensboston, sclex2(at)gmail.com

**Comment by sensboston** [comment]
OK

**Comment by Sclex** [comment]
@sensboston, больше чем час назад я получил от тебя сообщение "Test" и отправил тебе ответ на него. Уведомления о том, что мое сообщение тебе не доставлено, я не получал.

**Comment by sensboston** [comment]
Я его получил, но не стал отправлять ответ, чтобы не войти в бесконечный цикл 😜

**Comment by Sclex** [comment]
@sensboston, утилита update_fbe.exe у меня при запуске выдает ошибку. У меня ОС Windows XP Service Pack 3. Прилагаю снимок экрана.
![Clipboard35](https://user-images.githubusercontent.com/26221736/231729114-b4fbd50f-697f-4a3d-9a72-77e6e51b6101.png)

**Comment by Sclex** [comment]
В инструкции твоей все понятно, только вот утилита не работает.

**Comment by sensboston** [comment]
Утилита моя работает, но не на доисторических OS 😜 У меня XP не осталось, попробуй у себя перекомпилировать, только сначала укажи правильный путь к csc.exe (я в инструкции привожу пример)

**Comment by Sclex** [comment]
@sensboston, я установил этот .NET, с помощью него удалось успешно скомпилировать версию утилиты update_fbe, которая (версия) корректно отработала. Буду продолжать создание установочного пакета. Благодарю тебя за помощь!

**Comment by Sclex** [comment]
@sensboston, всё, удалось успешно собрать установочный пакет. Единственно, понадобилось в файле "MakeInstaller.bat" заменить "Program Files (x86)" на "Program Files". Спасибо.

**Comment by Sclex** [comment]
@sensboston, в окошке "О программе" после слова "сборка" почему-то написаны три вопросительных знака. Как это исправить?
![Clipboard36](https://user-images.githubusercontent.com/26221736/231769234-05083b7c-3bef-4a67-b6b1-7287cb3443f8.png)

**Comment by sensboston** [comment]
На счёт ??? - там у тебя что-то с локалью при преобразовании имени месяца, не хочу разбираться. Просто добавь в исходном файле после строки
```
var date = DateTime.Now.ToString("MMM dd yyyy");
date = "Apr 13 2023";
```
перекомпилируй и запусти еще разок.

**Comment by Sclex** [comment]
@sensboston, это сработало. Спасибо.
![Clipboard37](https://user-images.githubusercontent.com/26221736/231775488-3289b9b4-cb98-4251-bd95-4ce65d558d90.png)

**Comment by sensboston** [comment]
@Sclex, я подправил чуток update_fbe.cs/exe (указал явно CultureInfo как en-US), сейчас должно вписывать правильное название месяца on English - проверь у себя.

**Comment by Sclex** [comment]
@sensboston, да, теперь утилита работает правильно. Это облегчает дело. Спасибо.

**Comment by Sclex** [comment]
@sensboston, получившийся инсталл FBE не удается переслать почтой с Gmail-аккаунта. Если exe-файл пересылать как он есть (я даже изменил расширение на "exeexe"), то приходит ответ, что в файле предположительно вирус и сообщение не было доставлено адресату. Если запаковать файл в zip, выдается сообщение "Из соображений безопасности в Gmail нельзя использовать файлы такого типа, поскольку это нарушает правила Google в отношении исполняемых файлов и архивов". Бида-пичаль.

**Comment by sensboston** [comment]
OK, good! Я еще добавил и запушил папку **Utilities** в новый **Setup\Installer\Input**, чтобы собиралось без ошибок.

P.S. Но вот нужна ли там эта папка - вот в чём вопрос? 😉

**Comment by Sclex** [comment]
> P.S. Но вот нужна ли там эта папка - вот в чём вопрос?

Я думаю, вреда не будет.

**Comment by sensboston** [comment]
@Sclex, не нужно никуда и никому этот файл пересылать, я легко его могу у себя собрать. Ты делай все по инструкции: выложи его тут в Releases, измени файл [update.xml](https://github.com/sensboston/fictionbookeditor/edit/master/update.xml)  и отправь на тестирование (кто там тестировал у тебя? У меня сейчас нет ни времени, ни возможности - убегаю, сорри)

Не беспокойся - это не новый релиз ChatGPT, миллионы сразу-же качать не начнут 😜, так, что если там и остались баги, то ничего страшного.

Потом, думаю, нужно будет сделать анонс на флибусте/либрусеке для тех, кто FBE все-таки пользуется. Кстати, любопытно было бы глянуть статистику за последний год, сколько документов было сделано с помощью FBE, и сколько народу его использует, но пока не знаю, как это сделать. Слушай, а кроме FBE, есть какая-то сопоставимая по фичам и удобству тулза для fb2?

**Comment by Sclex** [comment]
> Слушай, а кроме FBE, есть какая-то сопоставимая по фичам и удобству тулза для fb2?

Мне ничего в таком роде не известно.

**Comment by Sclex** [comment]
> не нужно никуда и никому этот файл пересылать, я легко его могу у себя собрать.

Так я его *не тебе* посылал.

**Comment by Sclex** [comment]
В итоге залил файл на drive.google.com и послал ссылку для скачивания с этого Google Диск-а. Это работает.

**Comment by Sclex** [comment]
@sensboston, скомпилированный мной update_fbe.exe - будет ли работать в более поздних версиях Windows? Может, твою версию этой утилиты в GitHub-хранилище заменить на мою? Вдруг кто-то другой будет собирать инсталл FBE под Windows XP.

**Comment by sensboston** [comment]
@Sclex, если у тебя этот [exe-шник](https://github.com/sensboston/fictionbookeditor/raw/master/Setup/update_fbe.exe) работает, то и у меня он работает, ничего заменять не нужно.

**Comment by Sclex** [comment]
@sensboston, твой exe-шник (update_fbe.exe), который не работает у меня в Windows XP, может не работать под Windows XP и у кого-то другого (кроме меня).

**Comment by Sclex** [comment]
А, я не обратил внимание на ссылки. Счас проверю exe-шник по ссылке.

**Comment by sensboston** [comment]
Ты же написал, что:

> @sensboston, да, теперь утилита работает правильно. Это облегчает дело. Спасибо.

ничего не понимаю. Какой .NET ты установил?

**Comment by Sclex** [comment]
@sensboston, exe-файл, на который ты дал ссылку, у меня работает без ошибки. Значит, заменять файл в хранилище не нужно.

**Comment by Sclex** [comment]
> ничего не понимаю. Какой .NET ты установил?

Дело в том, что раньше я не использовал твою версию exe-шника, а скомпилировал ее сам из (нового) файла update_fbe.cs. Поэтому я не знал, что твоя новая версия exe-шника работает у меня корректно.

**Comment by Sclex** [comment]
@sensboston, почему-то твоя версии утилиты update_fbe.exe прописывает в FBE.exe дату "13 Apr 2023", хотя в Windows установлена текущая дата "15 Apr 2023". Возможно, "13 Apr" даже не прописывается, а остается от прошлого задания даты в файле.

**Comment by Sclex** [comment]
@sensboston, даже если я жестко прописываю в update_fbe.cs "date = "Apr 15 2023";", все равно после запуска утилиты в fbe.exe остается дата 13 Apr. Хотя время - меняется на текущее.

**Comment by Sclex** [comment]
@sensboston, а хотя все правильно работает. Как оказалось, я в батнике для компиляции скрипта прописал неверный путь.

**Comment by Sclex** [comment]
Выложил окончательную версию FBE Release 2.7.0 (build 15 Apr 2023) сюда:

https://github.com/sensboston/fictionbookeditor/releases/tag/2.7.0

Файл update.xml - обновил.

**Comment by Sclex** [comment]
О выпуске релиза FBE 2.7.0 [объявил](https://groups.google.com/g/fiction-book-editor/c/ZX2wXRUrp4U) в гугл-группе:

**Comment by sensboston** [comment]
Отлично, заодно, я и update проверил - работает (он только по дате работает, сравнивает внутреннюю дату билда с датой в xml, т.е. в будущем версию билда, теоретически, можно даже не менять).

**Comment by sensboston** [comment]
@Sclex, кстати, есть к тебе вопрос: в курсе ли ты, или кто-то из пользователей FBE, о "пасхалке" (впрочем, явно видимой), существующей в AboutBox-е? 😉 Хотел спросить еще лет 10 назад, но тогда было как-то неудобно... 
P.S. Я про 3D logo FB2, и отдельное окно с управлением, разворачивающееся из AboutBox-а по double click (help - клавиша '?')

**Comment by Sclex** [comment]
@sensboston, я знал, что можно поворачивать изображение в AboutBox-е, но что можно двойным щелчком открыть 3D-логотип в отдельном окне - не знал.

**Comment by Sclex** [comment]
@sensboston, когда-то давно я, наверное, знал про двойной щелчок по логотипу, но потом забыл. Я помню, что переписывался с тобой насчет этой "пасхалки".
