### ISSUE TITLE
Пробел перед процентом

### ISSUE THREAD

**Issue by ya158** [sensboston/fictionbookeditor#207]
Подскажите, пожалуйста, как убрать пробел перед процентом "%"?

**Comment by Sclex** [comment]
ya158, багтрекер - для того, чтобы сообщать о багах. С *вопросами* об FBE и его скриптах - обращайтесь в [гугл-группу fiction-book-editor](https://groups.google.com/g/fiction-book-editor).

**Comment by ya158** [comment]
https://ru.wikipedia.org/wiki/Википедия:Отбивка_знака_процента_от_предшествующей_цифры
Значит я неправильно сформулировал. FBE ставит пробел перед процентом. Это, согласно Википедии, неправильно. Это баг?

**Comment by Sclex** [comment]
@ya158, в качестве WYSIWYG-редактора FBE использует Internet Explorer. Может, в последних версиях этого браузера были какие-то изменения насчет пробела перед знаком процента?

**Comment by ya158** [comment]
Да, именно "Генеральную уборку" и имею в виду. Прошу прощения за неправильно составленный вопрос.

**Comment by Sclex** [comment]
В файле "02_Генеральная уборка.js" в строке, которая начинается с "var re53 = new" удалите знак процента. Тогда пробел перед знаками процента добавляться не будет.

Автор этого скрипта - jurgennt давно не занимается своими скриптами. Я не знаю, стоит ли исправление насчет знака процента делать для всех - может, какие-то пользователи хотят, чтобы пробел таки добавлялся.

**Comment by ya158** [comment]
Спасибо. Это я уже сам сообразил. Но хотелось бы, чтобы в автомате при запуске скрипта пробел перед процентом убирался бы.

**Comment by Sclex** [comment]
> хотелось бы, чтобы в автомате при запуске скрипта пробел перед процентом убирался бы.

Насчет этого я вам ничего не подскажу.

**Comment by ya158** [comment]
Жаль, но спасибо за ответ. А не подскажите, как можно обратиться к jurgennt с этим вопросом?

**Comment by Sclex** [comment]
Его е-мейл раньше был - jurgennt(at)gmail.com . Как сейчас - не знаю.
