### ISSUE TITLE
Как корректно собрать два файла fb2 в один (имеются сноски)?

### ISSUE THREAD

**Issue by LarisaFr** [sensboston/fictionbookeditor#208]
Как корректно собрать два файла fb2 в один (имеются сноски)? Заранее благодарна за ответ.

**Comment by Sclex** [comment]
Багтрекер для того, чтобы сообщать о багах и просить реализовать новый функционал. А вопросы про редактирование fb2-файлов следует задавать в гугл-группе [fiction-book-editor](https://groups.google.com/g/fiction-book-editor).
