### ISSUE TITLE
Error FBE Script

### ISSUE THREAD

**Issue by trade70** [sensboston/fictionbookeditor#214]
FictionBook Editor Release v2.7.5

Error at line:512
Unable to create an object by the object programming server
![2024-08-08_22-40-26](https://github.com/user-attachments/assets/af853d10-1e3f-4e65-b6ab-a40cdc553ab6)

**Comment by Sclex** [comment]
В FBE 2.7.5 имеется ошибка, из-за которой редактор работает лишь в случае наличия в операционной системе MSXML4. Чтобы FBE работал при установленном MSXML6, пожалуйста используйте более позднюю версию установочного пакета FBE (например, ту, которую я сегодня выпустил - 2.7.6).

**Comment by trade70** [comment]
Downloaded it, it works. Thank you!

**Comment by Sclex** [comment]
@trade70, you are welcome.
