### ISSUE TITLE
Не обновляется VERSIONINFO с 2.6.7.0

### ISSUE THREAD

**Issue by TaciturnShadow** [sensboston/fictionbookeditor#215]
В ресурсе VERSIONINFO уже много лет прописана версия 2.6.7.0. Обновляйте до актуальной, пожалуйста.

**Comment by Sclex** [comment]
@TaciturnShadow, возможно ли это сделать без перекомпилирования бинарных файлов?

**Comment by TaciturnShadow** [comment]
@Sclex, да, конечно. Например через [rcedit](https://github.com/electron/rcedit).
`rcedit-x86.exe FBE.exe --set-file-version 2.7.6 --set-product-version 2.7.6`

**Comment by Sclex** [comment]
@TaciturnShadow, у меня в WinXP при запуске команды, которую вы написали, выдает окошко с надписью "<...>\rcedit-x86.exe не является приложением Win32".

**Comment by TaciturnShadow** [comment]
@Sclex, можно взять более стуарую версию, в 2.0.0:
> Drops Windows XP support

[1.1.1](https://github.com/electron/rcedit/releases/tag/v1.1.1) должна работать нормально.

**Comment by Sclex** [comment]
@TaciturnShadow, да, теперь все получилось. Спасибо за советы! Собираюсь, когда буду выпускать новую версии установочного пакета FBE, задать в файле "fbe.exe" правильный номер версии.

**Comment by Sclex** [comment]
Я добавил в файл [readme.md](https://github.com/sensboston/fictionbookeditor/blob/master/Setup/readme.md) (это инструкция по сборке установочного пакета FBE) пункт о том, как поменять номер версии файла fbe.exe. Когда я собираю новую версию установочного пакета, то сверяюсь с файлом readme.md, чтоб ничего не забыть. Поэтому при сборке следующей версии инсталла, по идее, я не забуду изменить версию файла fbe.exe.
